# Generated by Django 5.2.1 on 2025-06-04 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_category_todo_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('session_type', models.CharField(choices=[('work', 'Work'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('interrupted', models.BooleanField(default=False)),
                ('todo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo_app.todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PomodoroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_duration', models.IntegerField(default=25)),
                ('short_break_duration', models.IntegerField(default=5)),
                ('long_break_duration', models.IntegerField(default=15)),
                ('long_break_interval', models.IntegerField(default=4)),
                ('notification_sound', models.BooleanField(default=True)),
                ('desktop_notification', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
